FROM alpine:3.17.2

LABEL maintainer="Maksim Bunegin"
LABEL description="PostgreSQL client (Alpine)"
LABEL website="https://github.com/steap0/docker-postgresql-client"

ARG CLIENT_VERSION ""

RUN apk --no-cache add postgresql${CLIENT_VERSION}-client

ENTRYPOINT [ "psql" ]
