name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Alpine-based Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.alpine
          build-args: |
            CLIENT_VERSION=${{ github.ref_name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/postgresql-client:psql-${{ github.ref_name }}
            ${{ secrets.DOCKER_USERNAME }}/postgresql-client:latest
          labels: |
            version=${{ github.ref_name }}
